services:
  tsdproxy:
    image: yichenchong/tsdproxy-cloudflare:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - <PATH_TO_YOUR_CONFIG_DIR>:/config
    restart: unless-stopped

volumes:
  datadir:
